#Create some aliases
  alias vpn="openconnect --protocol=gp vpn.univates.br"
  alias src="cd /usr/src"
  alias emacs="emacs --no-window-system ."

#Give transparence to the new terminal window
  transset-df --id "$WINDOWID" 0.9 >/dev/null #https://wiki.archlinux.org/index.php/Xterm#Automatic_transparency

#For style | Slow, but with style
  neofetch
