#Config for GUI
  export XDG_SESSION_TYPE=x11
  export GDK_BACKEND=x11

#Config for netbeans
  export _JAVA_AWT_WM_NONREPARENTING=1

#System monitoring for DWM
  while true; do
      ~/.config/pcinfo/script.sh
      sleep 5s
  done &

#keyboard layouts
  product=`cat /sys/devices/virtual/dmi/id/product_name`
  if [ "$product" == "MacBookAir1,1" ]; then
  
  fi
  if [ "$product" == "20BUS3V100" ]; then
    #Brasilian Keyboard ABNT2 ThinkPad T450
    setxkbmap -model thinkpad60 -layout br -variant abnt2
  fi
  if [ `grep obins < /proc/bus/input/devices | wc -l` > 0 ]; then
    #American keyboard with acentuation Obins Anne Pro
    setxkbmap -layout us -variant intl
  fi

#Transparency (Experimental)
  #xcompmgr -c &

#Set Random Wallpaper
  rm -rf ~/.fehbg
  feh --randomize --bg-fill ~/.config/wallpapers/

#Start DWM Window Manager
  [ "$(tty)" = "/dev/tty1" ] && ! exec dwm
