#Config for GUI
  export XDG_SESSION_TYPE=x11
  export GDK_BACKEND=x11

#Config for netbeans
  export _JAVA_AWT_WM_NONREPARENTING=1

#System monitoring for DWM
  while true; do
      ~/.config/pcinfo/script.sh
      sleep 5s
  done &

#keyboard layouts
  setxkbmap -layout us -variant intl #$American keyboard with acentuation
  #setxkbmap -layout br -variant abnt2 #Brasilian Keyboard ABNT2

#Transparency (Experimental)
  #xcompmgr -c &

#Set Random Wallpaper
  rm -rf ~/.fehbg
  feh --randomize --bg-fill ~/.config/wallpapers/

#Start DWM Window Manager
  [ "$(tty)" = "/dev/tty1" ] && ! exec dwm
